site_name: IS 640 Business Application Programming 
repo_url: https://github.com/on3moy/Python-Business-Application-Programming
repo_name: 'GitHub'

# https://www.mkdocs.org/user-guide/choosing-your-theme/
theme:
  name: material
  logo: img/pythonBW.ico
  # Dark Theme
  palette:
  - scheme: slate
    primary: 'black'
    accent: 'light blue'
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  # Light Theme
  - scheme: default
    primary: 'blue'
    accent: 'teal'
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  font:
    text: 'calibri'
    code: 'Consolas'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
nav:
  - Home: 'index.md'
  - Book:
    - Chapter 1: 'book/CH1/chapter1.md'
  - Python Crash Course: 'book/Notebooks/Python Crash Course.ipynb'
  - Install Python: 'installation.md'
  - MKDocsReference: 'Reference.md'

extra_css:
  - stylesheets/extra.css  

markdown_extensions:
  # Table of Contents Stay
  - toc:
      permalink: true
  # Ability to add notes in MD like !!! Some notes
  # - admonition
  - admonition
  - pymdownx.superfences
  # Highlights code like functions, etc.
  - codehilite
  - attr_list
  # Highlights additional features
  - pymdownx.highlight:
      # Add clickable code blocks
      anchor_linenums: true
  # Allows inline code highlights
  - pymdownx.inlinehilite
  # Adds expanded notes, hidden content
  - pymdownx.details
  # Add nice interface for tasks format
  - pymdownx.tasklist
  # HTML links become clickable
  - pymdownx.magiclink
  # Adds strike through
  - pymdownx.tilde
  - pymdownx.tabbed

plugins:
  - search
  - mknotebooks

copyright: Copyright &copy; 2024 Moy Patel