site_name: IS 640 Business Application Programming 
repo_url: https://https://github.com/on3moy/Python-for-Business-Apps
repo_name: 'GitHub'

# https://www.mkdocs.org/user-guide/choosing-your-theme/
theme:
  icon:
     annotation: material/arrow-right-circle
  name: material
  logo: img/Brackets.ico
  # Dark Theme
  palette:
  - scheme: slate
    primary: 'black'
    accent: 'light blue'
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  # Light Theme
  - scheme: default
    primary: 'white'
    accent: 'teal'
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  font:
    text: 'calibri'
    code: 'Consolas'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview  
    - navigation.path
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    
nav:
  - Home: 'index.md'
  - Book:
    - Chapter 1: 'book/CH1/chapter1.md'
    - Chapter 2: 
      - 2.1 Variable Assignments: 'book/CH2/2.1_VariableAssignments.md'
      - 2.2 Identifiers: 'book/CH2/2.2_Identifiers.md' 
      - 2.3 Objects: 'book/CH2/2.3_Objects.md'    
      - 2.4 Numeric Types: 'book/CH2/2.4_NumericTypes.md'  
      - 2.5 Arithmetic Expressions: 'book/CH2/2.5_ArithmeticExpressions.md'  
      - 2.6 Python Expressions: 'book/CH2/2.6_PythonExpressions.md' 
      - 2.7 Division & Modulo: 'book/CH2/2.7_DivisionModulo.md'
      - 2.8 Module Basics: 'book/CH2/2.8_ModuleBasics.md'  
      - 2.9 Math Module: 'book/CH2/2.9_MathModule.md'  
      - 2.10 Random Numbers: 'book/CH2/2.10_RandomNumbers.md' 
      - 2.11 Representing Text: 'book/CH2/2.11_RepresentingText.md' 
    - Chapter 3:
      - 3.1 String Basics: 'book/CH3/3.1_StringBasics.md'
      - 3.2 List Basics: 'book/CH3/3.2_ListBasics.md'
      - 3.3 Tuple Basics: 'book/CH3/3.3_TupleBasics.md'
      # - 3.4 Dictionary Basics: 'book/CH3/3.4_DictionaryBasics.md'
  - Python Crash Course: 'book/Notebooks/Python Crash Course.ipynb'
  - Install Python: 'installation.md'
  - MKDocsReference: 'Reference.md'

extra_css:
  - stylesheets/extra.css  

markdown_extensions:
  # Table of Contents Stay
  - toc:
      permalink: "⬅️"
  # Ability to add notes in MD like !!! Some notes
  # - admonition
  - admonition
  - pymdownx.superfences
  # Highlights code like functions, etc.
  - codehilite
  - attr_list
  # Highlights additional features
  - pymdownx.highlight:
      # Add clickable code blocks
      anchor_linenums: true
  # Allows inline code highlights
  - pymdownx.inlinehilite
  # Adds expanded notes, hidden content
  - pymdownx.details
  # Add nice interface for tasks format
  - pymdownx.tasklist
  # HTML links become clickable
  - pymdownx.magiclink
  # Adds strike through
  - pymdownx.tilde
  - pymdownx.tabbed

plugins:
  - search
  - mknotebooks

copyright: Copyright &copy; 2024 Moy Patel